config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'
  get 'pages/contact'
  get 'pages/how_it_works'
  get 'pages/team'
  
  root 'pages#index'

  devise_for :users
  resources :messages 

  resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
  
  resources :trips do
    collection do 
        get 'search'
    end
    resources :comments, except: [:show, :index]
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  # GET /trips
  # GET /trips.json
  
  def search
    @languages = Trip.pluck(:language).uniq
    @interests = Trip.pluck(:interests).uniq
    @destinations = Trip.pluck(:destination).uniq
    @filters = params.slice(:language,:interests)
    @search_param = params[:search].first rescue nil
    @language_param = params[:language]
    @intersts_param = params[:interests]

    if params[:search].present?
      @trips = Trip.where("destination LIKE :destination",  {:destination=> "%#{params[:search].first}%"}).where(@filters)
    else
      @trips = (Trip.where(@filters)) rescue (Trip.where(@filters).paginate(:page => params[:page], :per_page => 10))
    end
  end

  def index
    @trips = Trip.where(@filters)
    @languages = Trip.pluck(:language).uniq
    @interests = Trip.pluck(:interests).uniq
    @destinations = Trip.pluck(:destination).uniq
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @comments = Comment.where(trip_id: @trip.id)
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    trip_params["destination"].downcase!
    trip_params["language"].downcase!
    trip_params["interests"].downcase!
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:destination, :starting_date, :end_date, :interests, :user_id, :about_myself, :language)
    end

    def check_user
      if current_user.present? && Trip.find(params[:id]).user==current_user

      else
        flash[:error] = "This trip does not belong to you."
        redirect_to root_path
      end
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :destination %><br>
          <%= f.text_field :destination, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :interests %><br>
          <%= f.text_field :interests, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :starting_date %><br>
          <%= f.date_select :starting_date, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :end_date %><br>
          <%= f.date_select :end_date, class: "form-control" %>
        </div>
      </div>
    </div>
  <div class="form-group">
    <%= f.label :language %><br>
    <%= f.text_field :language, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :about_myself %><br>
    <%= f.text_area :about_myself, class: "form-control" %>
  </div>
   
  <div class="actions">
    <%= f.submit "Post My Trip", class: "btn btn-success" %>
  </div>
</div>
</div>
<% end %>

app/views/trips/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h1>Editing trip</h1>
  </div>
</div>
<%= render 'form' %>

    <div class="row">
  <div class="col-md-6 col-md-offset-2">
<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>
    </div>
</div>

app/views/trips/index.html.erb
<div style="margin-left: 5%; margin-bottom: 20px;">
  <%= link_to 'New Trip', new_trip_path, class: "btn btn-primary"  %>
</div>


<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_tag search_trips_path, :method=> :get, :class=> "center" do %>
          <%= select_tag :search, options_for_select(@destinations.uniq.sort.map {|destination| [destination.capitalize,destination]}), :id => "e1", :style=>"width:100%;", :multiple => true %><br>
          <div style="margin-top:15px">
            <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>

  <br><br>

  <div class="row">

    <div class="col-md-2">
      <p style="line-height:28px;">
        <fieldset>
        <legend><h5><b>Language Spoken</b></h5></legend>
        <div style="margin-left: 10px;">
          <% @languages.each do |language| %>
            <% if language.present? %>
              <%= link_to language.capitalize, search_trips_path(:language => language, :search => @search_param) %><br>
            <% end %>
          <% end %>
        </div>
        </fieldset>
      </p>
      <p style="line-height:28px;margin-top: 20px;">
        <fieldset>
        <legend><h5><b>Interests</b></h5></legend>
        <div style="margin-left: 10px;">
          <% @interests.each do |interest| %>
            <% if interest.present? %>
              <%= link_to interest.capitalize, search_trips_path(:search => @search_param, :interests => interest) %><br>
            <% end %>
          <% end %>
        </div>
        </fieldset>
      </p>
    </div>

    <div class="col-md-10">
      <% @trips.each do |trip| %>
        <div class="row">
         <div class="col-md-1">
            </div>

        <div class="col-md-5">
          <h3><%= "#{trip.user.first_name.capitalize} #{trip.user.last_name.capitalize}." %></h3>
          <a href="/trips/<%= trip.id %>">
            <table>
              <tr>
                <td><b>Destination</b></td>
                <td><div style="padding-left: 10px;"><%= trip.destination.capitalize %></div></td>
              </tr>
              <tr>
                <td><b>Interests</b></td>
                <td><div style="padding-left: 10px;"><%= trip.interests.capitalize %></div></td>
              </tr>
              <tr>
                <td><b>Language spoken</b></td>
                <td><div style="padding-left: 10px;"><%= trip.language.capitalize %></div></td>
              </tr>
              <tr>
                <td><b>About Myself</b></td>
                <td><div style="padding-left: 10px;"><%= truncate(trip.about_myself, :length => 200) %></div></td>
              </tr>
            </table>
          </a>
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-2">
           <%= link_to "Message", new_message_path(user: trip.user), class: "btn btn-primary" %>
        </div>
     </div><!-- end of row -->
    <% end %>
  </div><!-- end of col-md-10 -->
</div>
<%#= will_paginate @tutors, renderer: BootstrapPagination::Rails %>
<br>

  <script>
      $(document).ready(function() { $("#e1").select2({placeholder: "Where are you travelling to?", allowClear: true, maximumSelectionSize:1}); });
  </script>

app/views/trips/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h1>New trip</h1>
      </div>
    </div>

<%= render 'form' %>

    <div class="row">
  <div class="col-md-6 col-md-offset-2">
<%= link_to 'Back', trips_path %>
      </div>
    </div>

app/views/trips/search.html.erb
<div style="margin-left: 5%; margin-bottom: 20px;">
  <%= link_to 'New Trip', new_trip_path, class: "btn btn-primary"  %>
</div>


<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_tag search_trips_path, :method=> :get, :class=> "center" do %>
          <%= select_tag :search, options_for_select(@destinations.uniq.sort.map {|destination| [destination.capitalize,destination]}), :id => "e1", :style=>"width:100%;", :multiple => true %><br><br>
          <%= submit_tag "Search", :name=> nil, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <br><br>

  <div class="row">

    <div class="col-md-2">
      <p style="line-height:28px;">
      <fieldset>
        <legend><h5><b>Language Spoken</b></h5></legend>
        <div style="margin-left: 10px;">
          <% @languages.each do |language| %>
              <% if language.present? %>
                  <%= link_to language.capitalize, search_trips_path(:language => language, :search => @search_param) %><br>
              <% end %>
          <% end %>
        </div>
      </fieldset>
      </p>
      <p style="line-height:28px;margin-top: 20px;">
      <fieldset>
        <legend><h5><b>Interests</b></h5></legend>
        <div style="margin-left: 10px;">
          <% @interests.each do |interest| %>
              <% if interest.present? %>
                  <%= link_to interest.capitalize, search_trips_path(:search => @search_param, :interests => interest) %><br>
              <% end %>
          <% end %>
        </div>
      </fieldset>
      </p>
    </div>

    <div class="col-md-10">
      <% @trips.each do |trip| %>
          <div class="row">
            <div class="col-md-1">
            </div>

            <div class="col-md-5">
              <div>
                <h3><%= "#{trip.user.first_name.capitalize} #{trip.user.last_name.capitalize}." %></h3>
              </div>
              <p>
                <table>
                  <tr>
                    <td><b>Destination</b></td>
                    <td><div style="padding-left: 10px;"><%= trip.destination.capitalize %></div></td>
                  </tr>
                  <tr>
                    <td><b>Interests</b></td>
                    <td><div style="padding-left: 10px;"><%= trip.interests.capitalize %></div></td>
                  </tr>
                  <tr>
                    <td><b>Language spoken</b></td>
                    <td><div style="padding-left: 10px;"><%= trip.language.capitalize %></div></td>
                  </tr>
                  <tr>
                    <td><b>About Myself</b></td>
                    <td><div style="padding-left: 10px;"><%= truncate(trip.about_myself, :length => 200) %></div></td>
                  </tr>
                </table>

              </p>
            </div>
            <div class="col-md-1">
            </div>
            <div class="col-md-2">
              <%= link_to "Message", new_message_path(user: trip.user), class: "btn btn-primary" %>
            </div>
          </div><!-- end of row -->
      <% end %>
    </div><!-- end of col-md-10 -->
  </div>
</div>
<%#= will_paginate @tutors, renderer: BootstrapPagination::Rails %>
<br>

  <script>
      $(document).ready(function() { $("#e1").select2({placeholder: "Where are you travelling to?", allowClear: true, maximumSelectionSize:1}); });
  </script>

app/views/trips/show.html.erb
<div class="container">
  <div class-"row">
    <div class="col-md-7 col-md-offset-1">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Destination:</strong>
          <%= @trip.destination %>
        </p>

        <p>
          <strong>Starting date:</strong>
          <%= @trip.starting_date %>
        </p>

        <p>
          <strong>End date:</strong>
          <%= @trip.end_date %>
        </p>
        <p>
          <strong>Interests:</strong>
          <%= @trip.interests %>
        </p>
        <p>
          <strong>About Myself:</strong>
          <%= @trip.about_myself %>
        </p>
      
    </div>
    <div class="col-md-2">
      <%= link_to "Message", new_message_path(user: @trip.user), class: "btn btn-primary" %>
      <br><br>
      <% if current_user == @trip.user %>
          <%= link_to 'Edit', edit_trip_path(@trip), class: "btn btn-primary" %> 
      <% end %>
    </div>
  </div>
<div class="row">
        <div class="col-md-8 col-md-offset-1">
          <%= link_to 'Comment', new_trip_comment_path(@trip), class: "btn btn-primary" %>
              <table class="table">
                <thead>
                  <tr>
                    <th class="col-md-3"></th>
                    <th class="col-md-9"></th>
                  </tr>
                </thead>

                <tbody>

                  <% @comments.each do |comment| %>
                    <tr>
                      <td>
                        <h4>
                          <%= "#{comment.user.first_name.capitalize} #{comment.user.last_name.capitalize[0]}." %>
                        </h4>     
                        <p><%= comment.created_at.strftime("%-m/%-d/%y") %></p>      
                      </td>
                      <td>
                        <p><%= comment.comment %></p>
                        <!--<p><%#= h(comment.comment).gsub(/\n/, '<br/>').html_safe %></p>-->
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>  
  </div>
    
    