config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'
  get 'pages/contact'
  get 'pages/how_it_works'
  get 'pages/team'
  
  root 'pages#index'

  devise_for :users
  resources :messages 

  resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
  
  resources :trips do
    collection do 
        get 'search'
    end
    resources :comments, except: [:show, :index]
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
   before_filter :authenticate_user!
   before_filter :conversation, only: [:edit, :show, :update, :destroy]
   helper_method :mailbox, :conversation

  def index
    @conversations ||= current_user.mailbox.inbox.all
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def update
     if params[:reply_all].present?
      last_sender = @conversation.messages.last.sender
      last_receipt = @conversation.receipts_for(last_sender).last
      #logger.debug("form update: #{last_sender.inspect}")
      Rails.logger.debug("form is: #{last_receipt.inspect}")
      @receipt = current_user.reply_to_all(last_receipt, params[:body])

     redirect_to :action => :show
    end
  end

  private
 
  def mailbox
    @mailbox ||= current_user.mailbox
  end
 
  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end
 
  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end
 
  def message_params(*keys)
    fetch_params(:message, *keys)
  end
 
  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end


end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_get_messages_from_conversation.html.erb
<h2> looping through conversation.messages </h2>
<% conversation.messages.order('created_at DESC').each do |msg |%>
   
   <% if msg.sender == current_user %>
     <%= link_to 'You', msg.sender(msg.sender) %> <%= msg.body %>
   <% else %> <br>
     <%= link_to msg.sender.name, msg.sender(msg.sender) %> <%= msg.body %> <br>
   <% end %>

  <% end %>

<br>

app/views/conversations/_get_participants.html.erb
<br>

<% conversation.participants.each do |participant |%>
    <% if participant != current_user %>
     <%= participant.name %>
    <% end %>
 <% end %>

app/views/conversations/_messages_from_conversations_receipt.html.erb
<table class="table">
   <thead>
  </thead>
  <%= content_tag_for(:div, conversation.receipts_for(current_user).order(:created_at => :desc) ) do |receipt| %>
 
  <tbody>
    <tr>
      <td>
        <p><% message = receipt.message %>
         <% if message.sender == current_user %>
              <%#= link_to 'You', message.sender %>
          <%= link_to 'You' %>,  received <%= conversation.updated_at.strftime("%m/%e/%Y %I:%M %p") %>
            <%= simple_format h message.body %>
        
          <% else %>
           <%#= link_to message.sender.first_name, message.sender %>
           <%= link_to message.sender.first_name %>,
          received, <%= conversation.updated_at.strftime("%m/%e/%Y %I:%M %p") %>
           <%= simple_format h message.body %>
          <% end %></p>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
          
  

app/views/conversations/_reply_message_form.html.erb
<%= form_tag conversation_path(conversation), :method => :put do %>

  <div class="form-group">
    <%= text_area_tag :body, nil,:rows => 6, :cols=> 53, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit_tag 'reply', :name => :reply_all, class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>Inbox</h2>
      <table class="table">
        <thead>
          <tr>
            <td>Name</td>
            <td>Subject</td>
            <td>Sent Date</td>
          </tr>
        </thead>
        <% @conversations.each do |conversation| %>
          <tbody>
            <tr>
              <td><%= conversation.last_sender.first_name %><br></td>
              <td><%= link_to raw(truncate(strip_tags(conversation.last_message.subject), :length => 35)),conversation_path(conversation) %></td>
              <td><%= conversation.updated_at.strftime("%m/%e/%Y %I:%M %p") %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h2>Conversation with <%= @conversation.participants.map{|a| !(a.id==current_user.id) ? "#{a.first_name} #{a.last_name}" : nil }.compact!.first %></h2>
      <br>
<%= render 'reply_message_form' %>
     
<%= render 'messages_from_conversations_receipt' %>

      <%= link_to 'Back to conversations', conversations_path, class: "btn btn-primary" %>
    </div>
    <div class="col-md-4">
      
    </div>
  </div>
    