config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'
  get 'pages/contact'
  get 'pages/how_it_works'
  get 'pages/team'
  
  root 'pages#index'

  devise_for :users
  resources :messages 

  resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
  
  resources :trips do
    collection do 
        get 'search'
    end
    resources :comments, except: [:show, :index]
  end

end

app/views/layouts/_footer.html.erb
</div><!-- end of container from layout/application -->  
<br><br><br><br>
<div class="footer">
  <div class="jumbotron footer" style="background-color: #303036; margin-bottom: 0px">
    <div class="row">        
      <div class="col-md-8 col-md-offset-2">
          <p style="align:center;font-size: 15px "><%= link_to 'About', pages_about_path %> ㅣ <%= link_to 'Team', pages_team_path %></p>
          <p style="align: center; font-size: 13px;">English &nbsp;|&nbsp; Chinese &nbsp;|&nbsp; Korean</p>
          <br>
          
        <h5 style="align: right">Travellrs</h5>
        <p style="font-size:12px; align: right">Copyright © Travellrs All Rights Reserved</p>      
          
      </div><!-- end of col-md-6 -->
    </div><!-- end of row -->  
  </div><!-- end of jumbotron -->  
</div> <!-- end of footer -->

    

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Travellrs", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Find Travellers", trips_path %></li>
        <li><%= link_to "How it works", pages_how_it_works_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Inbox", conversations_path %></li>
        <li><%= link_to "Account Setting", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travellrs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

<%= render 'layouts/header' %>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <!--<p class="notice"><%#= notice %></p>-->
  <!--<p class="alert"><%#= alert %></p>-->
<%= yield %>
  
  <%= render 'layouts/footer' %>
  </div>
</body>
</html>